.\"
.TH KMSGSD 8 "November 2002" "Debian/GNU Linux"
.SH NAME
.B kmsgsd
\- separates iptables messages from all other kernel messages.
.SH SYNOPSIS
.B kmsgsd
.SH DESCRIPTION
.B kmsgsd
reads messages from the /var/lib/psad/psadfifo named pipe and prints any firewall
related log messages to the psad data file "/var/log/psad/fwdata".
.B psad
cannot detect port scans or other suspect traffic without kmsgsd running on
the machine.
.B kmsgsd
uses the psad.conf configuration file which by default is
located at /etc/psad/psad.conf, but a different path can be specified
on the command line.
.SH OPTIONS
.TP
.BR \-c\ \<config\-file>
Specify path to config file instead of using the default configuration file
/etc/psad/psad.conf.
.TP
.BR \-D
Dump the configuration values that
.B kmsgd
derives from /etc/psad/psad.conf (or other override files) on STDERR.
.TP
.BR \-h
Display usage information and exit.
.TP
.BR \-O\ \<config\-file>
Override config variable values that are normally read from the
/etc/psad/psad.conf file with values from the specified file.  Multiple
override config files can be given as a comma separated list.
.SH SEE ALSO
.BR psad (8),
.BR psadwatchd (8),
.SH AUTHOR
Michael Rash (mbr@cipherdyne.org)

This manual page was written by Daniel Gubser <daniel.gubser@gutreu.ch>
for the Debian GNU/Linux system (but may be used by others).
.SH DISTRIBUTION
.B psad
is distributed under the GNU General Public License (GPL), and the latest
version may be downloaded from
.B http://www.cipherdyne.org
