#!/bin/sh
#
# chkconfig: 345 05 99
# description: The Port Scan Attack Detector (psad)
# processname: psad
# config: psad

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
start)
	if grep -q psadfifo /etc/syslog.conf; then
		echo -n "Starting the psad daemons: "
		daemon /usr/sbin/psad -s /etc/psad/psad_signatures -a /etc/psad/psad_auto_ips
		echo
	else
	        echo "Syslog has not been configured to send kern.info messages to"
       		echo "/var/log/psadfifo.  Do you need to run the psad installer?"
	fi
	;;
stop)
	echo -n "Shutting down the psadwatchd monitoring daemon: "
	killproc psadwatchd
        echo
        echo -n "Shutting down the psad daemon: "
        killproc psad
	echo
	echo -n "Shutting down the kmsgsd daemon: "
	killproc kmsgsd
	echo
	echo -n "Shutting down the diskmond monitoring daemon: "
	killproc diskmond
	echo
	;;
status)
	status kmsgsd
	status psad 
	status psadwatchd
	status diskmond
	;;
restart|reload)
	$0 stop
	$0 start
	;;
	
*)
	echo "Usage: psad-init {start|stop|status|restart|reload}"
	exit 1
esac
